# ======================================================
#   AS²ERT Lab Website Configuration (Minimal Mistakes)
#   AI for Safe Software EngineeRing and Testing
# ======================================================

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "mint"   # try "sunrise" or "default" for color variation

# ------------------------------------------------------
# Site Identity
# ------------------------------------------------------
locale: "en-US"
title: "AS²ERT Lab"
title_separator: "-"
subtitle: "AI for Safe Software EngineeRing and Testing"
name: "AS²ERT Lab"
description: "My research combines program analysis and artificial intelligence to automate and enhance various software engineering tasks—such as testing, debugging, and program repair—with the goal of making software more reliable and development more cost-efficient."
url: "https://assert-lab.github.io"   # official domain for the lab
baseurl: ""                           # empty for organization sites
repository: "assert-lab/assert-lab.github.io"
logo: "/assets/images/logo.png"
masthead_title: " "                   # keeps the navbar clean
breadcrumbs: false
enable_copy_code_button: true
timezone: "America/Chicago"
copyright: "© AS²ERT Lab, The University of Texas at Dallas"

# ------------------------------------------------------
# Lab Lead / Author Profile
# ------------------------------------------------------
author:
  name: "Soneya Binta Hossain"
  avatar: "/assets/images/soneya.jpg"
  bio: "Assistant Professor, Department of Computer Science, The University of Texas at Dallas. My research combines program analysis and artificial intelligence to automate and enhance various software engineering tasks—such as testing, debugging, and program repair—with the goal of making software more reliable and development more cost-efficient."
  location: "Dallas, TX, USA"
  email: "sbhossain@utdallas.edu"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:soneya.hossain@utdallas.edu"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar-square"
      url: "https://scholar.google.com/citations?user="
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/assert-lab"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/soneyabintahossain/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/"

# ------------------------------------------------------
# Footer
# ------------------------------------------------------
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/assert-lab"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar-square"
      url: "https://scholar.google.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/soneyabintahossain/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/"
  since: "2025"

# ------------------------------------------------------
# Social and SEO
# ------------------------------------------------------
social:
  type: "Organization"
  name: "AS²ERT Lab"
  links:
    - "https://scholar.google.com/"
    - "https://github.com/assert-lab"
    - "https://www.linkedin.com/in/soneyabintahossain/"
    - "https://x.com/"

# ------------------------------------------------------
# Plugins (GitHub Pages–safe)
# ------------------------------------------------------
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# ------------------------------------------------------
# Pagination & Archives
# ------------------------------------------------------
paginate: 5
paginate_path: /page:num/
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# ------------------------------------------------------
# Markdown, Output, and Theme Behavior
# ------------------------------------------------------
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 1..6

sass:
  sass_dir: _sass
  style: compressed

# ------------------------------------------------------
# Default Front Matter
# ------------------------------------------------------
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
