# This is a basic workflow to help you get started with Actions

name: Link-Checker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-links:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Jekyll
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      # Install HTML-Proofer
      - name: HTML-Proofer
        run: bundle add html-proofer

      # Generate localhost.{crt, key}
      - name: "Generate localhost.{crt, key}"
        run: openssl req -x509 -out localhost.crt -keyout localhost.key -newkey rsa:2048 -nodes -sha256 -subj '/CN=localhost' -extensions EXT -config <( printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")

      - name: "Serve Website"
        run: bundle exec jekyll serve --ssl-key=./localhost.key --ssl-cert=./localhost.crt --detach

      - name: "Check for broken Links"
        run: bundle exec htmlproofer ./_site --only-4xx --checks 'Images,Scripts,Favicon,OpenGraph' # --enforce_https
        # see https://github.com/gjtorikian/html-proofer/blob/93ba616eb45b7ba844197fc29824995e8fcd2279/UPGRADING.md:
        # --check-html was removed in 4.0.0
        # --check_img_http was removed in 4.0.0
        
      - name: "Shutdown Website"
        run: pkill -f jekyll
